import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import {CsvProvider} from './context/CsvContext'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CsvProvider>
        <html lang="en">
          <body>
            {children}
          </body>
        </html>
      </CsvProvider>
    </ClerkProvider>
   
  );
}
